### ISSUE TITLE
Recommended increase tcp buffers is not correct

### ISSUE THREAD

**Issue by lfmunoz** [Jotschi/vertx-c10k-example#2]
Is there a reason for the the particular recommended setting 

```
# Increase tcp buffers
sysctl -w net.ipv4.tcp_mem="100000000 100000000 100000000"
```

or this is just a random change to get it to work? If  you read the documentation there are good reasons not to have all those numbers the same. The kernel does something slightly different under pressure. 

tcp_mem vector of 3 INTEGERs:

min - below this number of pages TCP is not bothered about its memory appetite

pressure - when amount of memory allocated by TCP exceeds this number of pages, TCP moderates its memory consumption and enters memory pressure mode, which is exited when memory consumption falls under “min”. The memory pressure mode presses down the TCP receive and send buffers for all the sockets as much as possible, until the low mark is reached again.

max - number of pages allowed for queuing by all TCP sockets.

**Comment by Jotschi** [comment]
I have not looked at tcp mem buffer settings in detail. It may not be needed to increase the tcp buffer sizes. It may be a good idea to add links to the documentation so that the individual settings and effects can be looked up.
